AWSTemplateFormatVersion: 2010-09-09
Parameters:
  ServiceName:
    Type: String
    Default: service-jc
    Description: A name for the service
  ImageUrl:
    Type: String
    Default: nginx
    Description: The url of a docker image that contains the application process that will handle the traffic for this service
  ContainerPort:
    Type: Number
    Default: 80
    Description: What port number the application inside the docker container is binding to
  ContainerCpu:
    Type: Number
    Default: 256
    Description: How much CPU to give the container. 1024 is 1 CPU
  ContainerMemory:
    Type: Number
    Default: 512
    Description: How much memory in megabytes to give the container
  DesiredCount:
    Type: Number
    Default: 2
    Description: How many copies of the service task to run
Resources: 
  VPC:
    Type: AWS::CloudFormation::Stack 
    Properties: 
      TemplateURL: https://bucket-juliocarpio.s3.amazonaws.com/VPC.yaml
  LoadBalancer: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      Parameters: 
        VPC: !GetAtt VPC.Outputs.VPCID
        PublicSubnetOne: !GetAtt VPC.Outputs.PublicSubnet1ID
        PublicSubnetTwo: !GetAtt VPC.Outputs.PublicSubnet2ID 
      TemplateURL: https://bucket-juliocarpio.s3.amazonaws.com/LoadBalancer.yaml
  ECS: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      Parameters: 
        VPCID: !GetAtt VPC.Outputs.VPCID 
        SN1ID: !GetAtt VPC.Outputs.PrivateSubnet1ID
        SN2ID: !GetAtt VPC.Outputs.PrivateSubnet2ID
        LoadBalancerSG: !GetAtt LoadBalancer.Outputs.LoadBalancerSG
      TemplateURL: https://bucket-juliocarpio.s3.amazonaws.com/ECS.yaml 
  Containers: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      Parameters: 
        ServiceName: !Ref ServiceName
        VPCID: !GetAtt VPC.Outputs.VPCID 
        ClusterName: !GetAtt ECS.Outputs.ClusterName 
        ContainerCpu: !Ref ContainerCpu
        ContainerMemory: !Ref ContainerMemory
        DesiredCount: !Ref DesiredCount
        ContainerPort: !Ref ContainerPort
        LoadBalancerListener: !GetAtt LoadBalancer.Outputs.PublicLBListener
      TemplateURL: https://bucket-juliocarpio.s3.amazonaws.com/Containers.yaml